/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_donation;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author shubh
 */
public class DonorAdmin extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form DonorAdmin
     */
    public DonorAdmin() {
        initComponents();
        con = Connect.ConnectDB();
        donorTable();
        donorRequestsTable();
        setExtendedState(DonorAdmin.MAXIMIZED_BOTH);
    }
    String adminusername;

    public DonorAdmin(String username) {
        initComponents();

        con = Connect.ConnectDB();
        donorTable();
        donorRequestsTable();
        setExtendedState(DonorAdmin.MAXIMIZED_BOTH);
        this.adminusername = username;
        jdonorAdmin.setText(adminusername);
        jdonorAdmin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Donodir = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        jdonarid = new javax.swing.JTextField();
        jname = new javax.swing.JTextField();
        jgender = new javax.swing.JTextField();
        jage = new javax.swing.JTextField();
        jaddr = new javax.swing.JTextField();
        jcity = new javax.swing.JTextField();
        jstate = new javax.swing.JTextField();
        jcon = new javax.swing.JTextField();
        jzip = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jmail = new javax.swing.JTextField();
        jSearch = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        donatereq = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jApprove = new javax.swing.JButton();
        jDecline = new javax.swing.JButton();
        jdid = new javax.swing.JTextField();
        jdonorAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(216, 235, 239));

        jTabbedPane1.setBackground(new java.awt.Color(216, 235, 239));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        Donodir.setBackground(new java.awt.Color(216, 235, 239));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor ID", "Name", "Gender", "Age", "Home Address", "City", "State", "Country", "Zipcode", "Phone Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Name:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Gender:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Age:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Home Address: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("City: ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("State:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Country:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Zipcode:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Phone Number:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Email:");

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Donor ID:");

        jdonarid.setEditable(false);

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.setToolTipText("");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DonodirLayout = new javax.swing.GroupLayout(Donodir);
        Donodir.setLayout(DonodirLayout);
        DonodirLayout.setHorizontalGroup(
            DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonodirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
            .addGroup(DonodirLayout.createSequentialGroup()
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonodirLayout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jphone))
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DonodirLayout.createSequentialGroup()
                                .addComponent(Search)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)))
                        .addGap(244, 244, 244)
                        .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DonodirLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jstate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jage))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jgender))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DonodirLayout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcon)
                                        .addComponent(jzip)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jname))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DonodirLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jaddr))
                                        .addGroup(DonodirLayout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jcity))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DonodirLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jdonarid, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(214, 214, 214))
            .addGroup(DonodirLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Create)
                .addGap(55, 55, 55)
                .addComponent(Delete)
                .addGap(53, 53, 53)
                .addComponent(Update)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DonodirLayout.setVerticalGroup(
            DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonodirLayout.createSequentialGroup()
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jdonarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DonodirLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonodirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Create)
                    .addComponent(Delete))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Donor Directory", Donodir);

        donatereq.setBackground(new java.awt.Color(216, 235, 239));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Donar ID", "Food Name", "Weight", "Expiry Date", "Time", "Date", "City", "Center Name", "Center Address", "Status", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jApprove.setText("Approve");
        jApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApproveActionPerformed(evt);
            }
        });

        jDecline.setText("Decline");
        jDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeclineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donatereqLayout = new javax.swing.GroupLayout(donatereq);
        donatereq.setLayout(donatereqLayout);
        donatereqLayout.setHorizontalGroup(
            donatereqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatereqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donatereqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(donatereqLayout.createSequentialGroup()
                        .addGroup(donatereqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdid, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(donatereqLayout.createSequentialGroup()
                                .addComponent(jApprove)
                                .addGap(40, 40, 40)
                                .addComponent(jDecline))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 771, Short.MAX_VALUE)))
                .addContainerGap())
        );
        donatereqLayout.setVerticalGroup(
            donatereqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donatereqLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(donatereqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApprove)
                    .addComponent(jDecline))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Donation Requests", donatereq);

        jdonorAdmin.setBackground(new java.awt.Color(216, 235, 239));
        jdonorAdmin.setFont(new java.awt.Font("NexaBlack", 1, 24)); // NOI18N
        jdonorAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(216, 235, 239));
        jLabel3.setFont(new java.awt.Font("NexaBlack", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jdonorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(922, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jdonorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1013, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(134, 197, 197));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food_donation/donate_food_0.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Take a bite out of hunger!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handlingString code here:


    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();

        jdonarid.setText(model.getValueAt(SelectIndex, 0).toString());
        jname.setText(model.getValueAt(SelectIndex, 1).toString());
        jgender.setText(model.getValueAt(SelectIndex, 2).toString());
        jage.setText(model.getValueAt(SelectIndex, 3).toString());
        jaddr.setText(model.getValueAt(SelectIndex, 4).toString());
        jcity.setText(model.getValueAt(SelectIndex, 5).toString());
        jstate.setText(model.getValueAt(SelectIndex, 6).toString());
        jcon.setText(model.getValueAt(SelectIndex, 7).toString());
        jzip.setText(model.getValueAt(SelectIndex, 8).toString());
        jphone.setText(model.getValueAt(SelectIndex, 9).toString());
        jmail.setText(model.getValueAt(SelectIndex, 10).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        DonorRegistration dr = new DonorRegistration();
        dr.setVisible(true);
    }//GEN-LAST:event_CreateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String User_Name = jdonarid.getText();
        String name = jname.getText();
        String gender = jgender.getText();
        int age = Integer.parseInt(jage.getText());
        String home_address = jaddr.getText();
        String city = jcity.getText();
        String state = jstate.getText();
        String country = jcon.getText();
        String zipcode = jzip.getText();
        String phone_number = jphone.getText();
        String email = jmail.getText();

        try {
            Statement stmt;

            if (rs.next()) {

                return;
            }
            String sql = "Delete from donor_registration WHERE User_Name=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, User_Name);
            pst.execute();
            donorTable();
            jdonarid.setText("");
            jname.setText("");
            jgender.setText("");
            jage.setText("");
            jaddr.setText("");
            jcity.setText("");
            jstate.setText("");
            jcon.setText("");
            jzip.setText("");
            jphone.setText("");
            jmail.setText("");

            JOptionPane.showMessageDialog(this, "Successfully Deleted", "DonorAdmin", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String donor_id = jdonarid.getText();
        String name = jname.getText();
        String gender = jgender.getText();
        int age = Integer.parseInt(jage.getText());
        String home_address = jaddr.getText();
        String city = jcity.getText();
        String state = jstate.getText();
        String country = jcon.getText();
        String zipcode = jzip.getText();
        String phone_number = jphone.getText();
        String email = jmail.getText();

        try {

            if (jdonarid.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Username", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jname.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Name", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }

            if (jage.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Age", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jaddr.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter address", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jcity.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter city", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jstate.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter state", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jcon.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter country", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jzip.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter zipcode", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jphone.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter phone number", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jmail.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Email", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }

            Statement stmt;
            stmt = con.createStatement();

            if (rs.next()) {

                return;
            }
            String sql = "Update  donor_registration set Name=?,Gender=?,Age=?,Address=?,City=?,State=?,Country=?,ZipCode=?,Phone_Number=?,Email=? WHERE User_Name=?";
            pst = con.prepareStatement(sql);

            pst.setString(1, name);
            pst.setString(2, gender);
            pst.setInt(3, age);
            pst.setString(4, home_address);
            pst.setString(5, city);
            pst.setString(6, state);
            pst.setString(7, country);
            pst.setString(8, zipcode);
            pst.setString(9, phone_number);
            pst.setString(10, email);
            pst.setString(11, donor_id);

            pst.execute();
            donorTable();
            jdonarid.setText("");
            jname.setText("");
            jgender.setText("");
            jage.setText("");
            jaddr.setText("");
            jcity.setText("");
            jstate.setText("");
            jcon.setText("");
            jzip.setText("");
            jphone.setText("");
            jmail.setText("");

            JOptionPane.showMessageDialog(this, "Successfully updated", "DonorAdmin", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String s = jSearch.getText();
        filter(s);


    }//GEN-LAST:event_SearchActionPerformed

    private void filter(String s) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(s));
    }

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();

        jdid.setText(model.getValueAt(SelectIndex, 1).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int SelectIndex = jTable2.getSelectedRow();

        jdid.setText(model.getValueAt(SelectIndex, 1).toString());


    }//GEN-LAST:event_jTable2MouseClicked

    private void jApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApproveActionPerformed
        // TODO add your handling code here:
        String donorid = jdid.getText();
        String comments = jTextArea1.getText();
        String approve = "Approved";
        try {

            String sql = "Update donation_details set status=?, comments=? where donorid=? ";

            pst = con.prepareStatement(sql);
            pst.setString(1, approve);
            pst.setString(2, comments);
            pst.setString(3, donorid);

            pst.execute();
            JOptionPane.showMessageDialog(this, "Successfully Updated", "Request", JOptionPane.INFORMATION_MESSAGE);
            jdid.setText("");
            jTextArea1.setText("");
            donorRequestsTable();
            

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }


    }//GEN-LAST:event_jApproveActionPerformed

    private void jDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeclineActionPerformed
        // TODO add your handling code here:
        String donorid = jdid.getText();
        String comments = jTextArea1.getText();
        String decline = "Declined";
        try {

            String sql = "Update donation_details status=?, comments=? where donorid=?";

            pst = con.prepareStatement(sql);
            pst.setString(1, decline);
            pst.setString(2, comments);
            pst.setString(3, donorid);

            pst.execute();
            JOptionPane.showMessageDialog(this, "Successfully Updated", "Request", JOptionPane.INFORMATION_MESSAGE);
            jdid.setText("");
            jTextArea1.setText("");
            donorRequestsTable();
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jDeclineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateRequests() {
        try {

            String qry = "Select * from donation_details";
            pst = con.prepareStatement(qry);
            rs = pst.executeQuery();

            if (rs.next()) {

                String request_id = String.valueOf(rs.getString("request_id"));
                String donor_od = String.valueOf(rs.getString("donorid"));
                String food_name = String.valueOf(rs.getString("food_name"));
                String weight = String.valueOf(rs.getString("weight"));
                //String wtype = String.valueOf(rs.getString("wtype"));
                String food_expirydate = String.valueOf(rs.getString("food_expirydate"));
                String time = String.valueOf(rs.getString("time"));
                String date = String.valueOf(rs.getString("date"));
                String city = String.valueOf(rs.getString("city"));
                String center_name = String.valueOf(rs.getString("center_name"));
                String center_address = String.valueOf(rs.getString("center_address"));
                String status = String.valueOf(rs.getString("status"));
                String comments = String.valueOf(rs.getString("comments"));

                String tbData[] = {request_id, food_name, weight, food_expirydate, time, date, city, center_name, center_address};
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.addRow(tbData);

            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    private void donorTable() {
        try {
            pst = con.prepareCall("Select * from donor_registration");
            rs = pst.executeQuery();
            ResultSetMetaData result = (ResultSetMetaData) rs.getMetaData();
            int c;
            c = result.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("User_Name"));
                    vector.add(rs.getString("Name"));
                    vector.add(rs.getString("Gender"));
                    vector.add(rs.getString("Age"));
                    vector.add(rs.getString("Address"));
                    vector.add(rs.getString("City"));
                    vector.add(rs.getString("State"));
                    vector.add(rs.getString("Country"));
                    vector.add(rs.getString("ZipCode"));
                    vector.add(rs.getString("Phone_Number"));
                    vector.add(rs.getString("Email"));

                }
                model.addRow(vector);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DonorAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void donorRequestsTable() {
        try {
            pst = con.prepareCall("Select * from donation_details");
            rs = pst.executeQuery();
            ResultSetMetaData result = (ResultSetMetaData) rs.getMetaData();
            int c;
            c = result.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("request_id"));
                    vector.add(rs.getString("donorid"));
                    vector.add(rs.getString("food_name"));
                    vector.add(rs.getString("weight"));
                    vector.add(rs.getString("food_expirydate"));
                    vector.add(rs.getString("time"));
                    vector.add(rs.getString("date"));
                    vector.add(rs.getString("city"));
                    vector.add(rs.getString("center_name"));
                    vector.add(rs.getString("center_address"));
                    vector.add(rs.getString("status"));
                    vector.add(rs.getString("comments"));

                }
                model.addRow(vector);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DonorAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Donodir;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JPanel donatereq;
    private javax.swing.JButton jApprove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDecline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSearch;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jaddr;
    private javax.swing.JTextField jage;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jcon;
    private javax.swing.JTextField jdid;
    private javax.swing.JTextField jdonarid;
    private javax.swing.JLabel jdonorAdmin;
    private javax.swing.JTextField jgender;
    private javax.swing.JTextField jmail;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jstate;
    private javax.swing.JTextField jzip;
    // End of variables declaration//GEN-END:variables
}
