/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_donation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author shubh
 */
public class LogisticAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LogisticAdmin
     */
      Connection con=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    public LogisticAdmin() {
        initComponents();
         setExtendedState(LogisticAdmin.MAXIMIZED_BOTH);
         addemp(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jhis = new javax.swing.JTabbedPane();
        DelP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRcid = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jRcnm = new javax.swing.JTextField();
        jRcadr = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
        jRorg = new javax.swing.JTextField();
        jFnm = new javax.swing.JTextField();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
        jRwt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel25 = new javax.swing.JLabel();
        jRdate = new javax.swing.JTextField();
        jdetails = new javax.swing.JButton();
        javax.swing.JLabel jLabel26 = new javax.swing.JLabel();
        jemid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        delemp = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
        jEmpid = new javax.swing.JTextField();
        jEpass = new javax.swing.JTextField();
        jEname = new javax.swing.JTextField();
        jEgen = new javax.swing.JTextField();
        jEage = new javax.swing.JTextField();
        jEadr = new javax.swing.JTextField();
        jEct = new javax.swing.JTextField();
        jEst = new javax.swing.JTextField();
        jEcon = new javax.swing.JTextField();
        jEzip = new javax.swing.JTextField();
        jEnum = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jSearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(134, 197, 197));
        jPanel1.setPreferredSize(new java.awt.Dimension(457, 494));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubh\\OneDrive\\Documents\\del.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Give to the ones in need !!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(216, 235, 239));

        jhis.setBackground(new java.awt.Color(216, 235, 239));
        jhis.setForeground(new java.awt.Color(0, 0, 0));
        jhis.setToolTipText("");
        jhis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DelP.setBackground(new java.awt.Color(216, 235, 239));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recipient ID", "Recipient Name", "Address", "Organization", "Food Name", "Weight", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Recipient ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Recipient Name:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Organization:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Food Name:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Weight:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Date:");

        jdetails.setBackground(new java.awt.Color(255, 255, 255));
        jdetails.setForeground(new java.awt.Color(0, 0, 0));
        jdetails.setText("Get Details");
        jdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdetailsActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Employee ID:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Assign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DelPLayout = new javax.swing.GroupLayout(DelP);
        DelP.setLayout(DelPLayout);
        DelPLayout.setHorizontalGroup(
            DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DelPLayout.createSequentialGroup()
                        .addComponent(jdetails)
                        .addGap(94, 94, 94)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DelPLayout.createSequentialGroup()
                                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRcid)
                                    .addComponent(jRcnm)
                                    .addComponent(jRcadr)
                                    .addComponent(jRorg)
                                    .addComponent(jFnm, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DelPLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DelPLayout.createSequentialGroup()
                                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRwt)
                                            .addComponent(jRdate, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(DelPLayout.createSequentialGroup()
                                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton2)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jemid)))))))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        DelPLayout.setVerticalGroup(
            DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdetails)
                    .addGroup(DelPLayout.createSequentialGroup()
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRcnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRcadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jRorg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jFnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jRwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jRdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jhis.addTab("Delivery Requests", DelP);

        delemp.setBackground(new java.awt.Color(216, 235, 239));
        delemp.setForeground(new java.awt.Color(0, 0, 0));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Password", "Name", "Gender", "Age", "Home Address", "City", "State", "Country", "Zipcode", "Phone Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable4MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Home Address:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Create Password:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Zipcode:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Country:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("City:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Phone Number:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Age:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Gender:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Employee ID:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("State:");

        Create.setBackground(new java.awt.Color(255, 255, 255));
        Create.setForeground(new java.awt.Color(0, 0, 0));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(255, 255, 255));
        Update.setForeground(new java.awt.Color(0, 0, 0));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 255, 255));
        Delete.setForeground(new java.awt.Color(0, 0, 0));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setForeground(new java.awt.Color(0, 0, 0));
        Search.setText("Search");
        Search.setToolTipText("");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delempLayout = new javax.swing.GroupLayout(delemp);
        delemp.setLayout(delempLayout);
        delempLayout.setHorizontalGroup(
            delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delempLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delempLayout.createSequentialGroup()
                        .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(delempLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(delempLayout.createSequentialGroup()
                                        .addComponent(Create)
                                        .addGap(42, 42, 42)
                                        .addComponent(Update)
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel14))))
                            .addGroup(delempLayout.createSequentialGroup()
                                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Search))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Delete)
                                    .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEct, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEpass, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEgen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEadr, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEst, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEcon, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEzip, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEnum, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(275, 275, 275))
                    .addGroup(delempLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        delempLayout.setVerticalGroup(
            delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delempLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delempLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(delempLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jEname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jEgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jEage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jEadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(delempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(Update)
                    .addComponent(Create))
                .addGap(149, 149, 149))
        );

        jhis.addTab("Delivery Employee", delemp);

        jPanel3.setBackground(new java.awt.Color(216, 235, 239));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recipient ID", "Recipient Name", "Address", "Orgnization", "Food  Name", "Weight", "Date", "Employee ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Get History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        jhis.addTab("History", jPanel3);

        jLabel2.setBackground(new java.awt.Color(216, 235, 239));
        jLabel2.setFont(new java.awt.Font("NexaBlack", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jhis))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jhis)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        
          
        if(jEmpid.getText().isBlank()||jEpass.getText().isBlank() ||jEname.getText().isBlank() || jEgen.getText().isBlank() || jEage.getText().isBlank()||  
                jEadr.getText().isBlank()|| jEct.getText().isBlank()|| jEst.getText().isBlank()|| jEcon.getText().isBlank()||jEzip.getText().isEmpty()|| jEnum.getText().isBlank()|| jEmail.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this,
                    "Please Enter All Fields",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
        }
        else{
           
            if(!Pattern.matches("^[A-Za-z\\s]{1,}[\\.]{0,1}[A-Za-z\\s]{0,}$",jEname.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Name  !!!");
            }
            else if(!Pattern.matches("^[0-9].*$",jEage.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Age !!!");
            }
            else if(!Pattern.matches("^[0-9].*$", jEzip.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Number !!!");
                
            }
            else if (!Pattern.matches("\\d{10}",jEnum.getText()))
            {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Number  !!!");
                
            }
            else if(!Pattern.matches("^[\\w\\-]([\\.\\w])+[\\w]+@([\\w\\-]+\\.)+[a-z]{2,4}$",jEmail.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Email !!!");
            }
            else{
                DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
                 String empid = jEmpid.getText();
        String Pass = jEpass.getText();
        String Name  = jEname.getText();
        String Gender =jEgen.getText();
        long Age = Long.parseLong(jEage.getText());
        String Addr = jEadr.getText();
        String City = jEct.getText();
        String State = jEst.getText();
        String Country = jEcon.getText();
        String Zip = jEzip.getText();
        long Phone =Long.parseLong(jEnum.getText());
        String Email = jEmail.getText();
        
        
                try {
                 con = Connect.ConnectDB();
                 String qry ="Insert into delemp (empid,pass,name,gender,age,addr,city,state,con,zip,num,email) value(?,?,?,?,?,?,?,?,?,?,?,?)";
                pst =con.prepareStatement(qry);
                pst.setString(1, empid);
                pst.setString(2, Pass);
                pst.setString(3, Name);
                pst.setString(4, Gender);
                pst.setLong(5, Age);
                pst.setString(6,Addr );
                pst.setString(7, City);
                pst.setString(8, State);
                pst.setString(9, Country);
                pst.setString(10, Zip);
                pst.setLong(11, Phone);
                pst.setString(12, Email);
                               
                              
                pst.execute();
                
                 JOptionPane.showMessageDialog(null, "Saved" );
                 
              
                } catch (SQLException ex) {
                    Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
        
        
        }
        
    
    }//GEN-LAST:event_CreateActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
           
        if(jEmpid.getText().isBlank()||jEpass.getText().isBlank() ||jEname.getText().isBlank() || jEgen.getText().isBlank() || jEage.getText().isBlank()||  
                jEadr.getText().isBlank()|| jEct.getText().isBlank()|| jEst.getText().isBlank()|| jEcon.getText().isBlank()||jEzip.getText().isEmpty()|| jEnum.getText().isBlank()|| jEmail.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this,
                    "Please Enter All Fields",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
        }
        else{
           
            if(!Pattern.matches("^[A-Za-z\\s]{1,}[\\.]{0,1}[A-Za-z\\s]{0,}$",jEname.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Name  !!!");
            }
            else if(!Pattern.matches("^[0-9].*$",jEage.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Age !!!");
            }
            else if(!Pattern.matches("^[0-9].*$", jEzip.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Number !!!");
                
            }
            else if (!Pattern.matches("\\d{10}",jEnum.getText()))
            {
                JOptionPane.showMessageDialog(this, "Please Enter Valid Number  !!!");
                
            }
            else if(!Pattern.matches("^[\\w\\-]([\\.\\w])+[\\w]+@([\\w\\-]+\\.)+[a-z]{2,4}$",jEmail.getText()))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Email !!!");
            }
            else{
                
                 String empid = jEmpid.getText();
        String Pass = jEpass.getText();
        String Name  = jEname.getText();
        String Gender =jEgen.getText();
        long Age = Long.parseLong(jEage.getText());
        String Addr = jEadr.getText();
        String City = jEct.getText();
        String State = jEst.getText();
        String Country = jEcon.getText();
        String Zip = jEzip.getText();
        long Phone =Long.parseLong(jEnum.getText());
        String Email = jEmail.getText();
                
                try {
                 con = Connect.ConnectDB();
                 String qry ="Update delemp set pass=?,name=?,gender=?,age=?,addr=?,city=?,state=?,con=?,zip=?,num=?,email=? where empid=?";
                pst =con.prepareStatement(qry);
                pst.setString(1, Pass);
                pst.setString(2, Name);
                pst.setString(3, Gender);
                pst.setLong(4, Age);
                pst.setString(5,Addr );
                pst.setString(6, City);
                pst.setString(7, State);
                pst.setString(8, Country);
                pst.setString(9, Zip);
                pst.setLong(10, Phone);
                pst.setString(11, Email);
                pst.setString(12, empid);               
                              
                pst.execute();
                
                model.setValueAt(empid, jTable4.getSelectedRow(), 0);
                model.setValueAt(Pass, jTable4.getSelectedRow(), 1);  
                model.setValueAt(Name, jTable4.getSelectedRow(), 2);
                model.setValueAt(Gender, jTable4.getSelectedRow(), 3);
                model.setValueAt(Age, jTable4.getSelectedRow(), 4);
                model.setValueAt(Addr, jTable4.getSelectedRow(), 5);
                model.setValueAt(City, jTable4.getSelectedRow(), 6);
                model.setValueAt(State, jTable4.getSelectedRow(), 7);
                model.setValueAt(Country, jTable4.getSelectedRow(), 8);
                model.setValueAt(Zip, jTable4.getSelectedRow(), 9);
                model.setValueAt(Phone, jTable4.getSelectedRow(), 10);
                model.setValueAt(Email, jTable4.getSelectedRow(), 11);
                
                
                
                 JOptionPane.showMessageDialog(null, "Information is updated!!!" );
                } catch (SQLException ex) {
                    Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
            }
     
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int Row = jTable4.getSelectedRow();
         
         if (Row <0)
          {
             JOptionPane.showMessageDialog(this,
                "No Row is selected! Please select one Row!!",
                "select Row",

                JOptionPane.ERROR_MESSAGE);

         }
         else{
             
             DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
              model.removeRow(Row);
              
              String Empid = jEmpid.getText();
              
                 
            try {
                String qry ="delete from  delemp where empid=?";
                pst =con.prepareStatement(qry);
                pst.setString(1, Empid);
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
             JOptionPane.showMessageDialog(null, "Deleted !!" );
             
             jEmpid.setText("");
        jEpass.setText("");
        jEname.setText("");
        jEgen.setText("");
        jEage.setText("");
        jEadr.setText("");
        jEct.setText("");
        jEst.setText("");
        jEcon.setText("");
        jEzip.setText("");
        jEnum.setText("");
        jEmail.setText("");
                
             
         }
        
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String s = jSearch.getText().toString();
        filter(s);
        
        
    }//GEN-LAST:event_SearchActionPerformed
     private void filter(String s)
        {
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(model);
              jTable4.setRowSorter(tr);
               tr.setRowFilter(RowFilter.regexFilter(s));
        } 
    
    
    
    private void jTable4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MousePressed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

        String teid = model.getValueAt(jTable4.getSelectedRow(), 0).toString();
        String tpass = model.getValueAt(jTable4.getSelectedRow(), 1).toString();
        String tn = model.getValueAt(jTable4.getSelectedRow(), 2).toString();
        String tg = model.getValueAt(jTable4.getSelectedRow(), 3).toString();
        String tag = model.getValueAt(jTable4.getSelectedRow(), 4).toString();
        String tadr = model.getValueAt(jTable4.getSelectedRow(), 5).toString();
        String tct = model.getValueAt(jTable4.getSelectedRow(), 6).toString();
        String tst = model.getValueAt(jTable4.getSelectedRow(), 7).toString();
        String tcn = model.getValueAt(jTable4.getSelectedRow(), 8).toString();
        String tz = model.getValueAt(jTable4.getSelectedRow(), 9).toString();
        String tph = model.getValueAt(jTable4.getSelectedRow(), 10).toString();
        String tem = model.getValueAt(jTable4.getSelectedRow(), 11).toString();

        jEmpid.setText(teid);
        jEpass.setText(tpass);
        jEname.setText(tn);
        jEgen.setText(tg);
        jEage.setText(tag);
        jEadr.setText(tadr);
        jEct.setText(tct);
        jEst.setText(tst);
        jEcon.setText(tcn);
        jEzip.setText(tz);
        jEnum.setText(tph);
        jEmail.setText(tem);

    }//GEN-LAST:event_jTable4MousePressed

    private void jdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdetailsActionPerformed
        // TODO add your handling code here:
            
          try {
              
              con =Connect.ConnectDB();
          
                String qry ="Select * from delreq";
              pst =con.prepareStatement(qry);
              rs = pst.executeQuery();
                while (rs.next())
                {
                    String rid=rs.getString(1);
                    String rname=rs.getString(2);                     
                     String radr=rs.getString(3);
                     String rorg=rs.getString(4);
                     String Fname=rs.getString(5);
                     String wt=rs.getString(6);
                     String dt=rs.getString(7);
                   
                    
                    String tbdata[]={rid,rname,radr,rorg,Fname,wt,dt};
                    DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
                    
                    model.addRow(tbdata);
                   
                }
          } catch (SQLException ex) {
              Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
          }
                
        
        
    }//GEN-LAST:event_jdetailsActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String rid = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String rname = model.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String radr = model.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String rorg = model.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String Fname = model.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String wt = model.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String dt = model.getValueAt(jTable1.getSelectedRow(), 6).toString();
        
        jRcid.setText(rid);
        jRcnm.setText(rname);
        jRcadr.setText(radr);
        jRorg.setText(rorg);
        jFnm.setText(Fname);
        jRwt.setText(wt);
        jRdate.setText(dt);
        
        
        
        
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                   String as ="pending";
        
                    String rid=jRcid.getText();
                    String rname=jRcnm.getText();
                     String radr=jRcadr.getText();
                     String rorg=jRorg.getText();
                     String Fname= jFnm.getText();
                     String wt=jRwt.getText();
                     String dt= jRdate.getText();
                     String eid=jemid.getText();
                     
                try {
                 con = Connect.ConnectDB();
                 String qry ="Insert into asigndel (empid,recpid,recpname,addr,org,foodnm,weight,deldate,status) value(?,?,?,?,?,?,?,?,?)";
                pst =con.prepareStatement(qry);
                 pst.setString(1, eid);
                pst.setString(2, rid);
                pst.setString(3, rname);
                pst.setString(4, radr);
                pst.setString(5, rorg);
                pst.setString(6, Fname);
                pst.setString(7,wt);
                pst.setString(8, dt);
                pst.setString(9, as);
               
               
                               
                              
                pst.execute();
                
                 JOptionPane.showMessageDialog(null, "Assigned" );
                 
              
                } catch (SQLException ex) {
                    Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
                     
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           try {
              
              con =Connect.ConnectDB();
          
                String qry ="Select * from asigndel";
              pst =con.prepareStatement(qry);
              rs = pst.executeQuery();
                while (rs.next())
                {
                    String rid=rs.getString(2);
                    String rname=rs.getString(3);                     
                     String radr=rs.getString(4);
                     String rorg=rs.getString(5);
                     String Fname=rs.getString(6);
                     String wt=rs.getString(7);
                     String dt=rs.getString(8);
                     String eid=rs.getString(1);
                   
                    
                    String tbdata[]={rid,rname,radr,rorg,Fname,wt,dt,eid};
                    DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
                    
                    model.addRow(tbdata);
                   
                }
          } catch (SQLException ex) {
              Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
          }
                
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
      public void addemp() 
    {
        
                
             
          try {
              
              con =Connect.ConnectDB();
          
                String qry ="Select * from delemp";
              pst =con.prepareStatement(qry);
              rs = pst.executeQuery();
                while (rs.next())
                {
                    String empid=rs.getString(1);
                    String pass=rs.getString(2);
                      String n = rs.getString(3);
                     String gen =rs.getString(4);
                     String age = rs.getString(5);
                     String adr=rs.getString(6);
                     String ct=rs.getString(7);
                     String st=rs.getString(8);
                     String cn=rs.getString(9);
                     String zp=rs.getString(10);
                     String nm=rs.getString(11);
                     String em=rs.getString(12);
                    
                    String tbdata[]={empid,pass,n,gen,age,adr,ct,st,cn,zp,nm,em};
                    DefaultTableModel model =(DefaultTableModel)jTable4.getModel();
                    
                    model.addRow(tbdata);
                   
                }
          } catch (SQLException ex) {
              Logger.getLogger(LogisticAdmin.class.getName()).log(Level.SEVERE, null, ex);
          }
                
             
          
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogisticAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogisticAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogisticAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogisticAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogisticAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JPanel DelP;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JPanel delemp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jEadr;
    private javax.swing.JTextField jEage;
    private javax.swing.JTextField jEcon;
    private javax.swing.JTextField jEct;
    private javax.swing.JTextField jEgen;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEmpid;
    private javax.swing.JTextField jEname;
    private javax.swing.JTextField jEnum;
    private javax.swing.JTextField jEpass;
    private javax.swing.JTextField jEst;
    private javax.swing.JTextField jEzip;
    private javax.swing.JTextField jFnm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jRcadr;
    private javax.swing.JTextField jRcid;
    private javax.swing.JTextField jRcnm;
    private javax.swing.JTextField jRdate;
    private javax.swing.JTextField jRorg;
    private javax.swing.JTextField jRwt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jSearch;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton jdetails;
    private javax.swing.JTextField jemid;
    private javax.swing.JTabbedPane jhis;
    // End of variables declaration//GEN-END:variables
}
